### PR TITLE
Initialized Files

### PR DESCRIPTION
**Pull request by hiroshi-tsutsui**
I configured the scripts so the file can be run by `npm run dev`.
Also fixed empty files that would throw error on build.

### CODE REVIEW

**Comment by hiroshi-tsutsui** [comment]
the changes I made about
`import { Icon } from '@mui/material';`

i just wanted to checkout icons from material ui but havent implemented anything yet because of the build error i found.
don't worry about this.

**Review by Sho-ki — APPROVED** [review]
LGTM

**Comment by hiroshi-tsutsui** [comment]
I added development build.
f578e6050b434fab6d088e5444b6ad96136c366c

**Review by Sho-ki — APPROVED** [review]
LGTM

**Pull request merged**
